# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deply Corenotes api
run-name: ${{ github.actor }} is deploying changes...
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout main branch
          uses: actions/checkout@v2
          with:
            ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build and Test
        run: npm run build

      # - name: Deploy to EC2
      #   run: |
      #     ssh-keyscan -H ${{ secrets.EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts
      #     chmod 600 path/to/your/private-key.pem
      #     ssh -i path/to/your/private-key.pem ec2-user@${{ secrets.EC2_INSTANCE_IP }} 'cd /corenotes-api && git pull origin/master && npm install && npm run build && pm2 restart corenotesapp'

      - name: Deploy to EC2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          #passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /corenotes-api
            git pull origin/master
            npm install
            npm run build
            pm2 restart corenotesapp